### ISSUE TITLE
Feature Request: Show timestamp and usernames for subsequent messages (Compact Mode)

### ISSUE THREAD

**Issue by raamdev** [wpsharks/slackmagic#1]
It would be nice (for consistency-sake) to see, in Compact Mode, the username on _all_ messages by that user, along with the timestamp. Right now, subsequent messages don't include the timestamp or the username:

![2014-07-01_18-58-15](https://cloud.githubusercontent.com/assets/53005/3450100/4807e7dc-0173-11e4-8ae4-a20a2d9e8b72.png)

**Comment by jaswrks** [comment]
Thanks! I agree.

@raamdev writes...

> Disabled compact mode and reloaded the browser tab; still not seeing the icon for each GitHub notification

---- Roger that. Thanks! Does anything show up red in your developer "console"?

**Comment by raamdev** [comment]
> Does anything show up red in your developer "console"?

Nope, nothing red.

**Comment by jaswrks** [comment]
This has been implemented in the latest dev branch.
Please confirm this is working for you now.

**Comment by raamdev** [comment]
Works great! :) Thanks!

![2014-07-02_12-53-52](https://cloud.githubusercontent.com/assets/53005/3459154/7a02e746-0209-11e4-83b5-d0e1ea78175a.png)

**Comment by jaswrks** [comment]
Awesome, thanks for confirming.
