### ISSUE TITLE
Subsequent GitHub git notifications don't include icon

### ISSUE THREAD

**Issue by raamdev** [wpsharks/slackmagic#2]
It looks like, at least in Compact Mode, subsequent GitHub git notifications (related to commits, pull requests, etc.) don't show subsequent messages with their own GitHub icon:

![2014-07-01_19-17-54](https://cloud.githubusercontent.com/assets/53005/3450214/17d5638e-0176-11e4-834a-c0456e738a77.png)

However, GitHub Issue comment notifications do show subsequent messages with their own icon:

![2014-07-01_19-18-03](https://cloud.githubusercontent.com/assets/53005/3450217/28f8ed0c-0176-11e4-8cb7-8b669eba57a0.png)

**Comment by raamdev** [comment]
This is not limited to Compact Mode, as the same is shown with the Clean Theme.

**Comment by jaswrks** [comment]
> It looks like, at least in Compact Mode, subsequent GitHub git notifications (related to commits, pull requests, etc.) don't show subsequent messages with their own GitHub icon:

Roger that. Here is another issue I am seeing that is somewhat related. Wrong/default avatar there; and no name for some reason yet to be determined.

![2014-07-01_17-12-52](https://cloud.githubusercontent.com/assets/1563559/3450821/33b29cd8-0186-11e4-9284-f364ee7d976d.jpg)

**Comment by jaswrks** [comment]
This must be an asynchronous issue, because it is working on my side and not on yours. Might need to adjust the event timeout to account for any missing nodes in the first pass.

![2014-07-01_17-17-35](https://cloud.githubusercontent.com/assets/1563559/3450848/cf5e91be-0186-11e4-861f-d5845e3ca122.jpg)

**Comment by jaswrks** [comment]
This should be resolved in the latest dev branch.
Please confirm this is working for you now. Thanks!

**Comment by raamdev** [comment]
Confirmed. Working great! Thanks!

![2014-07-02_12-55-26](https://cloud.githubusercontent.com/assets/53005/3459170/b1bd307e-0209-11e4-9147-cbc00b4a039b.png)

**Comment by jaswrks** [comment]
Reopening this. I'm seeing a jumpy behavior whenever I myself post multiple messages in a row. It's working properly in real-time chat, but there is a jumpy behavior there I'd like to resolve.

**Comment by jaswrks** [comment]
This should be resolved in the latest dev branch.
