### ISSUE TITLE
SlackMagic in Native App

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/slackmagic#3]
@raamdev On a Mac, it seems the native app uses a kiosk window that is powered by Safari. In theory, we should be able to port this extension to Safari without much trouble and get this working in the native app too.

I have not worked with Safari extensions in the past, but it's all JavaScript/CSS. In theory, it should just be a matter of getting this extension (i.e. the manifest, or whatever) into a format that Safari demands for it's extensions.

Referencing: https://developer.apple.com/library/safari/documentation/Tools/Conceptual/SafariExtensionGuide/Introduction/Introduction.html

**Comment by raamdev** [comment]
Awesome! I wonder how we'd use a Safari extension in the Slack app...

Also, I saw this on the page you referenced... might complicate things?

> Important: To develop extensions for Safari, you need to sign up for the Safari developer program online, at http://developer.apple.com. You need a signed certificate before your extension can be installed

**Comment by jaswrks** [comment]
> Also, I saw this on the page you referenced... might complicate things?

Thanks. Maybe. It looks like it is free so maybe not.
Referencing: https://developer.apple.com/programs/safari/

**Comment by jaswrks** [comment]
Referencing: https://developer.apple.com/devcenter/safari/index.action

**Comment by jaswrks** [comment]
Good grief this was buried deep...
- Getting the certificate...
  https://developer.apple.com/programs/safari/gettingstarted/
  _I submitted the application for WebSharks, Inc. I will post the certificate on Slack when it arrives._
- Building the extension; **which looks like a piece of cake**, given there is wizard for it. ha
  https://developer.apple.com/library/safari/documentation/tools/conceptual/safariextensionguide/UsingExtensionBuilder/UsingExtensionBuilder.html

**Comment by jaswrks** [comment]
Just waiting on the certificate to arrive and then we should be able to test this. Whether it will get picked up by the kiosk window is yet to be seen :-)

![2014-07-01_22-13-12](https://cloud.githubusercontent.com/assets/1563559/3452300/0ffa7eee-01b0-11e4-8f3e-d0a8943d5b28.jpg)

**Comment by jaswrks** [comment]
Guy tried to call this morning to verify my certificate. Missed the call. Hopefully tomorrow.

**Comment by jaswrks** [comment]
![2014-07-07_11-44-04](https://cloud.githubusercontent.com/assets/1563559/3501094/81f5795c-0612-11e4-8438-5caddd01a04f.jpg)

![2014-07-07_12-08-11](https://cloud.githubusercontent.com/assets/1563559/3501097/86c01d70-0612-11e4-8d19-e0509fbc4a69.jpg)

**Comment by jaswrks** [comment]
I will come back to this again soon.

**Comment by jaswrks** [comment]
Oh, nice! I got access to all the latest Yosemite stuff too. I will have to check that out eventually.

**Comment by raamdev** [comment]
Darn! I requested early access to the Yosemite developers preview but never heard back from them. :(

**Comment by jaswrks** [comment]
Taking a closer look at this now.

**Comment by jaswrks** [comment]
The Safari extension has been built. You can use the source for the extension (available in the dev branch) inside the `~.safariextension` directory. Or (easier), I will send you the Safari extension package file privately while we test this. The package file you can simply drag n' drop onto Safari to install it easily.

NOTE: It seems to be working in the Safari browser just fine (after a refresh of the Slack UI); but sadly, it is NOT working in the native app. I'm not sure it will be possible, but we could experiment a little and see if there is a way to hack it together.

**Comment by jaswrks** [comment]
If we can't get this working another solution might be to use this: http://fluidapp.com/

**Comment by jaswrks** [comment]
Closing this issue. Raam and I got this working on Mac OS X using Fluid: http://fluidapp.com/
~ See video tutorial here if you are interested in trying this on your Mac:
https://websharks.slack.com/files/jaswsinc/F02ET87NR/slackmagic.mp4

**Comment by raamdev** [comment]
@jaswsinc Can that video be shared publicly? If so, I'd like to link to it from the README.md file for this project.

**Comment by jaswrks** [comment]
Ah, that would be cool. Only thing is, the video contains a few customer email addresses and what-not, so probably better if those don't go public. Sorry about that! I did not think of making it public when I did this before.

**Comment by raamdev** [comment]
> the video contains a few customer email addresses and what-not, so probably better if those don't go public.

No worries. :) I updated the SlackMagic README.md file with some screenshots and basic instructions for getting it working in a FluidApp, so I think that's good enough.
