### ISSUE TITLE
(Compact Mode) Bot message single-line inconsistancy

### ISSUE THREAD

**Issue by raamdev** [wpsharks/slackmagic#6]
There's a weird bug where some of the bot messages that should be on one line get split into two lines:

![2014-07-03_12-23-52](https://cloud.githubusercontent.com/assets/53005/3472706/eebc38b0-02ce-11e4-95d9-e72ad158aabc.png)
![2014-07-03_12-24-14](https://cloud.githubusercontent.com/assets/53005/3472707/effb0134-02ce-11e4-856b-9808d610fb06.png)

**Comment by jaswrks** [comment]
I am seeing this too. Can you do me a favor? Please add the following style to your `/slackmagic/styles/slacktastic.css` file. That should resolve it. However, it also makes the Compact Mode MORE compact. Can you tell me if that is preferable to you or no? If not, please let me know. That way when I update the extension I will have it the way that you prefer in compact mode. I use the clean mode myself.

```
#msgs_div .copy_only
{
    display : none !important;
}
```

**Comment by jaswrks** [comment]
Also try...

```
#msgs_div .copy_only
{
    display : none !important;
}
.dense_theme #msgs_div .message_sender:after
{
    content: ':';
    display: inline-block;
    margin-right: 3px;
}
```

**Comment by raamdev** [comment]
This seems to have done the trick:

``` css
#msgs_div .copy_only
{
    display : none !important;
}
```

![2014-07-03_18-38-59](https://cloud.githubusercontent.com/assets/53005/3476595/d6f93a0a-0302-11e4-8bb7-edd91b514de5.png)

**Comment by jaswrks** [comment]
Great, thank you. The latest dev branch includes this improvement.
